
server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
  datasource:
    password: ${MYSQL_ROOT_PASSWORD}
    username: ${MYSQL_ROOT_USER}
    url: jdbc:mysql://localhost:3306/ponto?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
logging:
  level:
    org.springframework.security: debug

keycloak:
  auth-server-url: http://localhost:8280/auth
  realm: usuarios
  public-client: false
  resource: ponto
  ssl-required: external
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  enabled: true