
server:
  port: 8081

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  datasource:
    password: thiago
    username: root
    url: jdbc:mysql://localhost:3306/ponto?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true